//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Shop
{
    using System;
    using System.Collections.Generic;
    
    public partial class client_info
    {
        public int id { get; set; }
        public string surname { get; set; }
        public string first_name { get; set; }
        public string patronymic { get; set; }
        public string phone_number { get; set; }
        public string email { get; set; }

        public client_info()
        {
        }
        public client_info(string firstName, string surname, string patromymic, string phoneNumber, string email)
        {
            id = 0;
            first_name = firstName;
            this.surname = surname;
            patronymic = patromymic;
            phone_number = phoneNumber;
            this.email = email;
        }

        public client_info(int id, string firstName, string surname, string patromymic, string phoneNumber, string email)
        {
            this.id = id;
            first_name = firstName;
            this.surname = surname;
            patronymic = patromymic;
            phone_number = phoneNumber;
            this.email = email;
        }
    }
}
